default: &default
  adapter: postgresql
  encoding: utf8
  reconnect: true
  pool: 5
  username: postgres
  password: postgres
  host: localhost

development:
  <<: *default
  database: promobug_development
production:
  <<: *default
  database: promobug_production
test:
  <<: *default
  database: promobug_test
